apiVersion: batch/v1
kind: Job
metadata:
  name: compile-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        karpenter.sh/nodepool: amd-neuron-trn1
      serviceAccountName: appsimulator
      schedulerName: my-scheduler
      containers:
      - name: app
        image: 891377065549.dkr.ecr.us-west-2.amazonaws.com/model:amd64-neuron
        imagePullPolicy: Always
        volumeMounts:
          - name: dshm
            mountPath: /dev/shm
          #- name: s3-flux-pvc
          #  mountPath: /model
        command: 
        - /bin/bash
        - "-exc"
        - |
          set -x
          pip install --upgrade pip
          pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com
          pip install --upgrade neuronx-cc transformers_neuronx neuronx_distributed transformers torch-neuronx accelerate triton protobuf
          git clone -b v0.6.x-neuron https://github.com/aws-neuron/upstreaming-to-vllm.git
          cd upstreaming-to-vllm
          pip install -r requirements-neuron.txt
          VLLM_TARGET_DEVICE="neuron" && pip install -e .
          pip install sentence_transformers
          pip install --upgrade "transformers==4.45.2"
          python /compile-vllm.py 
          while true; do sleep 3600; done
        resources:
          limits:
            memory: "465Gi"
            aws.amazon.com/neuron: "8"
          requests: 
            memory: "465Gi"
            aws.amazon.com/neuron: "8"
        env:
        - name: PYTHONWARNINGS
          value: "ignore::UserWarning"
        - name: MODEL_NAME
          value: "deepseek-ai/DeepSeek-R1-Distill-Llama-70B"
        - name: MAX_MODEL_LEN
          value: "128"
        - name: MAX_NUM_SEQS
          value: "1"
        - name: TENSOR_PARALLEL_SIZE
          value: "32"
        - name: COMPILED_MODEL_NAME
          value: "yahavb/DeepSeek-R1-Distill-Llama-70B-nxd-tp32-len128-bs1"
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secrets
              key: HUGGINGFACE_TOKEN
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
        #- name: s3-flux-pvc
        #  persistentVolumeClaim:
        #    claimName: s3-flux-pvc
