apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: high-priority
value: 1000000  # Higher value means higher priority
globalDefault: false
description: "This is a high-priority class for important workloads."
