---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sd21-trn1-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sd21-trn1-serve 
  minReplicaCount: 1
  triggers:
    - type: aws-cloudwatch
      metadata:
        namespace: AWS/ApplicationELB
        metricName: HTTPCode_Target_2XX_Count
        expression: SELECT SUM(HTTPCode_Target_2XX_Count) FROM SCHEMA("AWS/ApplicationELB", LoadBalancer,TargetGroup) WHERE TargetGroup = 'targetgroup/k8s-default-sd21trn1-14ba69eb11/ef458ef788392cba' AND LoadBalancer = 'app/sd21mulitaccelserve/ebcc2480432c6bad'
        targetMetricValue: "65"
        minMetricValue: "1"
        metricUnit: Count
        awsRegion: us-west-2
      authenticationRef:
        name: keda-trigger-auth-aws-credentials
