apiVersion: karpenter.sh/v1beta1
kind: NodePool
metadata:
  name: amd-nvidia-g5
spec:
  disruption:
    budgets:
    - nodes: 10%
    consolidationPolicy: WhenUnderutilized
    expireAfter: 720h
  limits:
    cpu: 1000
  template:
    spec:
      nodeClassRef:
        name: amd-nvidia-g5
      requirements:
      - key: kubernetes.io/arch
        operator: In
        values:
        - amd64
      - key: karpenter.k8s.aws/instance-gpu-name
        operator: In
        values:
        - a10g
      - key: karpenter.k8s.aws/instance-size
        operator: In
        values:
        - 12xlarge
      - key: karpenter.sh/capacity-type
        operator: In
        values:
        - on-demand
---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: amd-nvidia-g5
spec:
  amiFamily: AL2 
  role: $KarpenterNodeRole
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: $KarpenterDiscoveryTag
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 300Gi
        volumeType: gp3
        encrypted: true

