apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bert-gpu-2
  name: bert-gpu-2
spec:
  selector:
    matchLabels:
      app: bert-gpu-2
  template:
    metadata:
      labels:
        app: bert-gpu-2
    spec:
      nodeSelector:
        karpenter.sh/nodepool: amd-nvidia-g5
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      containers:
      - name: app
        image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/stablediffusion:amd64-cuda
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /app
            name: workdir
        command: ["/run-bert.sh"]
        args: ["run-bert"]
        resources:
          limits:
            nvidia.com/gpu: 1
        ports:
          - containerPort: 8000
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 60
          periodSeconds: 10
        env:
        - name: DEVICE
          value: "cuda"
        - name: MODEL_ID
          value: "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
        - name: COMPILED_MODEL_ID
          value: "distilbert/distilbert-base-uncased-finetuned-sst-2-english"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: HUGGINGFACE_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-secrets
              key: HUGGINGFACE_TOKEN
      volumes:
      - name: workdir
        emptyDir: {}
      - name: dshm
        emptyDir:
          medium: Memory
